=== remy228/WebAnalyticsTool/trending.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT trending_news_topics (trending+)>
	<!ELEMENT trending (keyword,frequency_score, query_filter, url)>
		<!ELEMENT keyword (#PCDATA)>		
		<!ELEMENT frequency_score (#PCDATA)>
		<!ELEMENT query_filter (#PCDATA)>
		<!ELEMENT url (#PCDATA)>
		<!ENTITY CS "computer science">
	
			<!ATTLIST frequency_score fading CDATA "1">

=== remy228/WebAnalyticsTool/sample_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trending_news_topics SYSTEM "trending.dtd">

<trending_news_topics><trending><keyword>the</keyword><frequency_score>6</frequency_score><query_filter></query_filter><url></url></trending><trending><keyword>the</keyword><frequency_score>6</frequency_score><query_filter></query_filter><url>http://rss.slashdot.org/~r/Slashdot/slashdot/~3/-ivA_SbGtbo/microsoft-buys-into-dna-data-storage</url></trending><trending><keyword>the</keyword><frequency_score>6</frequency_score><query_filter></query_filter><url>http://www.reddit.com/r/technology/comments/4grpkw/comcast_raises_limit_on_how_much_netflix/</url></trending><trending><keyword>of</keyword><frequency_score>3</frequency_score><query_filter></query_filter><url></url></trending><trending><keyword>of</keyword><frequency_score>3</frequency_score><query_filter></query_filter><url>http://rss.slashdot.org/~r/Slashdot/slashdot/~3/-ivA_SbGtbo/microsoft-buys-into-dna-data-storage</url></trending><trending><keyword>and</keyword><frequency_score>3</frequency_score><query_filter></query_filter><url></url></trending><trending><keyword>and</keyword><frequency_score>3</frequency_score><query_filter></query_filter><url>http://rss.slashdot.org/~r/Slashdot/slashdot/~3/-ivA_SbGtbo/microsoft-buys-into-dna-data-storage</url></trending><trending><keyword>and</keyword><frequency_score>3</frequency_score><query_filter></query_filter><url>http://www.reddit.com/r/technology/comments/4grpkw/comcast_raises_limit_on_how_much_netflix/</url></trending><trending><keyword>in</keyword><frequency_score>3</frequency_score><query_filter></query_filter><url></url></trending><trending><keyword>in</keyword><frequency_score>3</frequency_score><query_filter></query_filter><url>http://hosted2.ap.org/APDEFAULT/3d281c11a96b4ad082fe88aa0db04305/Article_2016-04-27-10%20Things%20to%20Know-Thursday/id-868c27a7aea64bc7bc38a58c62b450cf</url></trending><trending><keyword>to</keyword><frequency_score>3</frequency_score><query_filter></query_filter><url>http://rss.slashdot.org/~r/Slashdot/slashdot/~3/-ivA_SbGtbo/microsoft-buys-into-dna-data-storage</url></trending><trending><keyword>to</keyword><frequency_score>3</frequency_score><query_filter></query_filter><url>http://www.reddit.com/r/technology/comments/4grpkw/comcast_raises_limit_on_how_much_netflix/</url></trending><trending><keyword>on</keyword><frequency_score>3</frequency_score><query_filter></query_filter><url>http://rss.slashdot.org/~r/Slashdot/slashdot/~3/-ivA_SbGtbo/microsoft-buys-into-dna-data-storage</url></trending><trending><keyword>on</keyword><frequency_score>3</frequency_score><query_filter></query_filter><url>http://feeds.reuters.com/~r/reuters/topNews/~3/487mneLjEhE/us-mideast-crisis-syria-demistura-idUSKCN0XO2YR</url></trending><trending><keyword> </keyword><frequency_score>3</frequency_score><query_filter></query_filter><url>http://feeds.reuters.com/~r/reuters/topNews/~3/487mneLjEhE/us-mideast-crisis-syria-demistura-idUSKCN0XO2YR</url></trending><trending><keyword>Armenian</keyword><frequency_score>3</frequency_score><query_filter></query_filter><url>http://hosted2.ap.org/APDEFAULT/3d281c11a96b4ad082fe88aa0db04305/Article_2016-04-27-10%20Things%20to%20Know-Thursday/id-868c27a7aea64bc7bc38a58c62b450cf</url></trending><trending><keyword>United</keyword><frequency_score>2</frequency_score><query_filter></query_filter><url>http://rss.slashdot.org/~r/Slashdot/slashdot/~3/-ivA_SbGtbo/microsoft-buys-into-dna-data-storage</url></trending><trending><keyword>a</keyword><frequency_score>2</frequency_score><query_filter></query_filter><url>http://hosted2.ap.org/APDEFAULT/3d281c11a96b4ad082fe88aa0db04305/Article_2016-04-27-10%20Things%20to%20Know-Thursday/id-868c27a7aea64bc7bc38a58c62b450cf</url></trending><trending><keyword>a</keyword><frequency_score>2</frequency_score><query_filter></query_filter><url>https://en.wikinews.org/wiki/Bus_explosion_in_Armenian_capital_kills_two</url></trending></trending_news_topics>
